### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by reallinfo** [cotoami/cotoami#104]
Hello!

I am a graphic designer. I like to contribute by designing a logo for open source software. 
I want to design a logo for cotoami. What do you think?

Also, If there is a your logo idea, I can design it.

**Comment by marubinotto** [comment]
Hi, 

That's really brilliant! I'll definitely merge it if you send a PR ;-)

**Comment by reallinfo** [comment]
Oh okay :D which one do you prefer? Left or right?

**Comment by marubinotto** [comment]
I prefer the left one. Could you create two versions of it, one with the "COTOAMI" text and the other without it?

**Comment by reallinfo** [comment]
Sure, I provided all the files and i sent a pr. https://github.com/cotoami/cotoami/pull/107


Is there anything else you want? Logo design for another project... etc.

**Comment by marubinotto** [comment]
Thank you! I've added a comment to the PR.

> Is there anything else you want?

If I find another one, I'll let you know, thanks ;-)

**Comment by marubinotto** [comment]
@reallinfo I noticed the final version doesn't have the rays of light (lines), which your original proposal has. I think it might not be clear what the icon is without the lines. Do you still have the files of the original version?

**Comment by reallinfo** [comment]
Sure, I still have the original files. do you want the lines to be white?

**Comment by reallinfo** [comment]
I can send a new pr if you want. (with white lines)

**Comment by marubinotto** [comment]
@reallinfo 

> do you want the lines to be white?

You mean making it a lighter color? I think it doesn't need to be changed from the orginal.

By "the rays of light (lines)", I mean this lines:

<img width="282" alt="original-logo" src="https://user-images.githubusercontent.com/764015/42545366-6d301eba-84f2-11e8-8e3a-ae20320ab4ce.png">

The logo image represents "light bulb", doesn't it?

**Comment by reallinfo** [comment]
Oh, sorry.  I forgot to add the light rays. I will send a new pr soon.

**Comment by reallinfo** [comment]
I updated the all files. Please check it.

https://github.com/cotoami/cotoami/pull/108

**Comment by marubinotto** [comment]
@reallinfo Thanks! I merged the pr.
