### ISSUE TITLE
I'd like to install cotoami on the host in docker

### ISSUE THREAD

**Issue by kroschu** [cotoami/cotoami#110]
but receive error:

 `,[info] Running CotoamiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
,[info] Running migrations on start...
,[info] Already up
,
,> cotoami@1.0.0 watch /app/assets
,> NPM_BIN=$(npm bin) brunch watch --stdin
,
,15:51:09 - info: Using outdated versions of phoenix, phoenix_html, babel-brunch, brunch, clean-css-brunch, uglify-js-brunch, sass-brunch, elm, elm-brunch, elm-format, elm-github-install, trying to update to match package.json versions
,15:51:09 - info: Installing packages with npm...
,15:54:41 - info: compiling
,Elm compile: src/Main.elm, in elm, to ../vendor/elm.js
,Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
,saschatimme/elm-phoenix existed, but I could not find anything when I went to
,look up the published versions of this package.`

I use Dockerfile:
`FROM cotoami/cotoami-elixir:1.6
ENV APP_PORT 4000
EXPOSE ${APP_PORT}

RUN npm cache clean 
RUN npm install -g brunch

ADD . /app
WORKDIR /app

RUN mix deps.get
RUN cd assets && npm install

CMD ["/bin/bash", "-c", "PORT=${APP_PORT}  mix phx.server"]`

and run it:
`docker run  -dit --restart unless-stopped --name coto -e COTOAMI_SMTP_SERVER="127.17.0.8" -e COTOAMI_DEV_REPO_HOST="127.17.0.6" 5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=cotoami_dev -e COTOAMI_NEO4J_HOST="127.17.0.7" -e COTOAMI_REDIS_HOST="127.17.0.5" -v $PWD:/app -p 4000:4000 -t kroschu/armhf-alpin-cotoami
`
help install service please.

**Comment by marubinotto** [comment]
You can use `cotoami/cotoami` image instead of `cotoami/cotoami-elixir` image which does not contain the app .

https://hub.docker.com/r/cotoami/cotoami/

**Comment by kroschu** [comment]
Thanks a lot.
