### ISSUE TITLE
Translation of the interface into Ukrainian

### ISSUE THREAD

**Issue by kroschu** [cotoami/cotoami#111]
I'm trying to translate your app, because the target audience does not know English. But changes files in /assets/elm/src/App/Modals  directory do not give results. 
![13421073-586a-4cc7-8135-abea2c2034ba](https://user-images.githubusercontent.com/10142684/45104255-5958a000-b13a-11e8-92ab-c5387545bffa.jpeg)
Where I make mistake?

**Comment by kroschu** [comment]
Yes, of course, thanks for your work.

**Comment by marubinotto** [comment]
@kroschu Hi, I just added i18n support to the develop branch.

You can add a translation as a single `*.elm` file. 

https://github.com/cotoami/cotoami/tree/develop/assets/elm/src/App/I18n/Translations

For example, if you want to add a Ukrainian translation, add `Uk.elm` file in the directory and modify [Translate.elm](https://github.com/cotoami/cotoami/blob/develop/assets/elm/src/App/I18n/Translate.elm). 

Could you send a pull request? I'll be glad to test and merge it.
