### ISSUE TITLE
How to launch cotoami with docker

### ISSUE THREAD

**Issue by But2ene** [cotoami/cotoami#126]
I would like to just try cotoami on my computer but the commands to run in 
issue #110 and the readme are not perfectly clear for me.
I got the same error as #125 when I run it from my computer. 
`docker run cotoami/cotoami` creates a lots of errors

How can I launch cotoami/cotoami docker container from command line?

**Comment by marubinotto** [comment]
I've added a new way to launch Cotoami with Docker. Just one single command:

```
$ wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh | bash
```

See also:
https://github.com/cotoami/cotoami#launch-your-own-server-with-docker
