### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by nukedone** [cotoami/cotoami#141]
I set up the instance of the app with the docker script. The site is visible at local address. However, the MailDev at port 8080 does not show any messages for the signup request. I have the port 25 opened on the router. Where do I go wrong?

**Comment by nukedone** [comment]
OK. I figured I need to pass the SMTP host parameter to the MailDev. How do I do that in Docker?

**Comment by marubinotto** [comment]
Did you launch it with the command presented in README?

```
wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh | bash
```

It'll configure all the containers including maildev, so you shouldn't need to configure it yourself.

**Comment by nukedone** [comment]
I did everything, but when I enter my email to sign up, it doesn't arrive
in my inbox.

**Comment by nukedone** [comment]
looks like disabling ifw on my virtual machine has solved the problem.

**Comment by nukedone** [comment]
disable ufw on your ubuntu machine and you are allowed to ask for one email address only for one singup link.
