### ISSUE TITLE
Cotoami Scraper for localhost

### ISSUE THREAD

**Issue by devsecur** [cotoami/cotoami#149]
If I try to use the cotoami scraper for the docker test version, I get an error "Error: Forbidden" on posting cotoami:

![Bildschirmfoto von 2019-08-04 13-46-05](https://user-images.githubusercontent.com/32730503/62423175-3756fd00-b6be-11e9-86bf-3ba92e96313a.png)

I have configured the cotoami URL to http://127.0.0.1:4000

**Comment by devsecur** [comment]
If i try to open the api endpoint itself, I get an "Internal server error"

![Bildschirmfoto von 2019-08-04 14-08-44](https://user-images.githubusercontent.com/32730503/62423503-6d49b080-b6c1-11e9-9207-b2a2cac72a4b.png)

**Comment by marubinotto** [comment]
Sorry for the lack of documentation. You need to configure your Cotoami container via an environment variable `COTOAMI_ADDITIONAL_VALID_ORIGINS`. Set it to `chrome-extension://` to allow the Cotoami Scraper to access the Cotoami server.

For example, if you setup your Cotoami with the command in the README, modify your `docker-compose.yml` file to add a line `COTOAMI_ADDITIONAL_VALID_ORIGINS: chrome-extension://` to the `environment` section of the `cotoami` service and restart the container by:

```
$ COMPOSE_PROJECT_NAME=cotoami COTOAMI_VERSION="v0.23.0" docker-compose up -d --no-deps cotoami
```

**Comment by devsecur** [comment]
Hi @marubinotto  thank you very much it worked. Additionally, I had to set the COTOAMI_HOST, because of the following error:

`cotoami_1   | 13:15:33.577 request_id=2ms0i9nte5hqq4fhto000353 [info] invalid host header: 127.0.0.1:4000`

So my command is as following:

```
COMPOSE_PROJECT_NAME=cotoami COTOAMI_VERSION="v0.23.0" COTOAMI_HOST="127.0.0.1" docker-compose up
```

assuming the configuration for the plugin is `127.0.0.1`
