### ISSUE TITLE
Linking Cotos to Cotonoma by tagging

### ISSUE THREAD

**Issue by devsecur** [cotoami/cotoami#150]
First of all, I'm realy curious about Cotoami because I love your concept to build knowledge by connecting collaboration and organization. I've been working with [tiddlymap](http://tiddlymap.org/) so far, but your concept is amazing, thank you.

It would be great to have the possibility to fast pin a Coto to multiple Cotonoma by "tagging" the Coto while editing with the Cotonoma, just as input field under the Coto itself. This could offer a more Coto centric workflow - currently it's hard for me to organize a new field of knowledge only by pinning or linking

![Bildschirmfoto von 2019-08-04 13-58-37](https://user-images.githubusercontent.com/32730503/62423343-07105e00-b6c0-11e9-8aef-e4a07ddbc951.png)

**Comment by marubinotto** [comment]
Hi @devsecur, thank you for your kind words and feedback!

The development version has a reposting feature and we've been testing it at https://cotoa.me

https://twitter.com/cotoami/status/1144988793226661888

It allows to repost your Cotos to other Cotonomas and works like tagging. It doesn't work as multiple pinning, but I think more suitable for situations where you need tag-like classification.

**Comment by devsecur** [comment]
Hi @marubinotto thank you for the fast feedback on my feature request. I've checked out the develop tag docker and tested the reposting feature and I think it's great for enhancing the collaborative approach of Cotoami.

But in the graph view, the connection to both cotonoma isn't visible, so I can't navigate over the coto to the connected cotonoma. 

![Bildschirmfoto von 2019-08-05 15-53-39](https://user-images.githubusercontent.com/32730503/62469749-3777fb00-b799-11e9-9d07-43f8dfb86def.png)
![Bildschirmfoto von 2019-08-05 15-55-45](https://user-images.githubusercontent.com/32730503/62469898-84f46800-b799-11e9-9ef2-5731b2f66aa1.png)


As a user with a tagging like connection concept, I would like to see all relevant tags (or reposts) of a Coto to determine it's relevance and it's context to reduce complexity.

Basicly, it would be great to have some flexibility in the graph view to define the steps of distance and the kind of edges (and nodes?) to view (show distance 2 with tagging edges)

**Comment by marubinotto** [comment]
The distinction between connections and post/repost relationships is important in Cotoami. The former provides a way to create structured content or conceptual structures as in [Concept Maps](http://cmap.ihmc.us/docs/conceptmap.php) while the latter provides more like categorical grouping which makes a hierarchy of Cotonomas. 

The graph view is designed to provide a way to browse a structure of Coto's network, not for a categorical hierarchy. Maybe we need another view to browse post/repost relationships or a hierarchy of Cotonomas.
