### ISSUE TITLE
Mail notification for new posts

### ISSUE THREAD

**Issue by devsecur** [cotoami/cotoami#153]
Is there a notification function for new posts? Would be great to have a daily mail summary for new posts in known cotonomas not to miss anything just as in Microsoft Teams

**Comment by marubinotto** [comment]
There's a Cotonoma Watchlist feature:

[Release v0\.20\.0 \- Cotonoma Watchlist · cotoami/cotoami](https://github.com/cotoami/cotoami/releases/tag/v0.20.0)

Before implementing more detailed notification, I think about adding a membership feature to Cotonomas, which will be another basis for notification.

**Comment by devsecur** [comment]
Watchlist works fine as well. Membership feature sounds great. 

Would be great to get the watchlist notifications as mail (and mobile notification) as well
