### ISSUE TITLE
Can't running cotoami with Docker

### ISSUE THREAD

**Issue by li0817** [cotoami/cotoami#163]
Since I'm not a programmer, I apologize if the question is too low level. 
I've spent a little time learning Docker for this, but I still haven't figured out how to use it to run Cotoami, and I've been tinkering with it for hours, so I'm here for help.

My system is Win10 and there is only one Linux command in the documentation

> wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh | bash

It seems to download the soucre code and run the run.sh.

Although I have Wget installed for Windows, I don't know what to do to run that sh file, I tried to download the entire source code directly and unzip it, run that sh file, and a Docker-Compose file appears, not sure how to use it.

When I scroll to the bottom of the document, see there is a image, so I pull a Cotoami image down to the local, details as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/27659768/89097685-a8d1a480-d413-11ea-946c-98fe68b3b349.png)

I start this image with no errror pops up, seems all things went swimmingly. Yet a few seconds later, it automatically stopped, I don't know if I am not operating right.
 
![XE}X%6MJBZU8NZB(H9Z~(OL](https://user-images.githubusercontent.com/27659768/89097505-04029780-d412-11ea-956c-1525df015e96.gif)
I couldn't read the log and searched some of the words in it that seemed to be keywords, but I was really unable to find anything useful.

Or just impossible for windows to run Cotoami since there exist just one linux command in the document. Or maybe I should create a dockerfile from cratch to use it ?

**Comment by marubinotto** [comment]
Sorry for the lack of documentation on Windows.

> a Docker-Compose file appears, not sure how to use it.

You need `docker-compose` command on your machine to launch Cotoami. From your screenshots, your machine should have this command. If executing `docker-compose -v` displays version info, then your environment is ready to run Cotoami.

Move to the folder where the `docker-compose.yml` file resides and execute the following command:

```
docker-compose up -d
```

After launching is completed, you should be able to access the server at http://localhost:4000

**Comment by li0817** [comment]
> Move to the folder where the `docker-compose.yml` file resides and execute the following command:
> 
> ```
> docker-compose up -d
> ```
> 
> After launching is completed, you should be able to access the server at http://localhost:4000

The docker-compose file generated by run.sh is completely empty, if the command `docker-compose up -d` is executed, it will return an error, should I fill in this 'yml' file myself?
![image](https://user-images.githubusercontent.com/27659768/89712856-270ae980-d9c6-11ea-9531-b5a464413781.png)

I originally used the start run.sh command, but since the file was empty, I suspected there might be a problem. So I opened git bash, and used the sh and bash commands to try it out. Although it did show a port 4000 address, but the page wouldn't work.
Maybe it is because the error is still there, it says the file cannot be none.

![image](https://user-images.githubusercontent.com/27659768/89713024-6259e800-d9c7-11ea-9c68-ee12ec573214.png)

By the way, the image on that hub isn't really needed, is it? Or should I going to use it to do some port mapping or something?

**Comment by marubinotto** [comment]
> The docker-compose file generated by run.sh is completely empty

To make `run.sh` work correctly, you need a Linux environment on your Windows machine, for example, by installing [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). But you don't need `run.sh` to launch Cotoami, instead download a complete `docker-compose.yml` file from the below:

https://raw.githubusercontent.com/cotoami/cotoami/develop/launch/docker-compose.yml

And save the file into any folder you like and execute `docker-compose up -d` in the folder. You should see the output in the console like: 

```
$ docker-compose up -d
Creating volume "cotoami_postgres-data" with default driver
Creating volume "cotoami_neo4j-data" with default driver
Creating cotoami_maildev_1  ... done
Creating cotoami_neo4j_1    ... done
Creating cotoami_postgres_1 ... done
Creating cotoami_redis_1    ... done
Creating cotoami_cotoami_1  ... done
```

Then, open http://localhost:4000 by your web browser.

**Comment by li0817** [comment]
Thanks, problem solved, but another problem arose when I registered/logged in.
I have tried four different email addresses and have been waiting for several hours, yet I haven't received any emails and I made sure it wasn't in the spam. Is the failure to send/receive emails my problem?

**Comment by marubinotto** [comment]
Oh sorry, I forgot to mention that. You can use any email address to sign-up/in, but you need to check sign-up/in mails at http://localhost:8080

Currently, Cotoami supports sign-up/in only via email, so by default when you launch it with `docker-compose`, a dummy mail server is enabled and that can be accessed via http://localhost:8080

**Comment by li0817** [comment]
Thanks! It's all good now.
By the way, update the documentation lest someone else, especially layman, doesn't catch on. It's easy to use actually:)

**Comment by marubinotto** [comment]
Thank you @li0817 for your feedback! Making it easy to get started for personal use is definitely one of the high-priority issues I will tackle in future versions.
