### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by li0817** [cotoami/cotoami#164]
I've been using it for a while, but some icons are missing from the outset. Finally I feel a little inconvenient to use so I came here.

① Pin button missing
![image](https://user-images.githubusercontent.com/27659768/94158313-d5a2b500-feb4-11ea-99dc-52342dcfdf93.png)

② Link button missing
![image](https://user-images.githubusercontent.com/27659768/94158709-4c3fb280-feb5-11ea-8abc-62252f37c948.png)
I need to click Plus button(add a sub-coto) to create new connection. I can't connect two exsiting Cotos.
![image](https://user-images.githubusercontent.com/27659768/94159268-edc70400-feb5-11ea-9321-17c2444e8e02.png)

③ All the windows are missing Close button, I always need to press Esc to close windows.
![image](https://user-images.githubusercontent.com/27659768/94159121-c5d7a080-feb5-11ea-8435-3266b3c0d122.png)

④ Shuffle icon missing
![image](https://user-images.githubusercontent.com/27659768/94161544-5dd68980-feb8-11ea-8ed9-b3c50c831900.png)

⑤ Other icon missing
When I hit the three dots of each Coto,
![image](https://user-images.githubusercontent.com/27659768/94158966-99238900-feb5-11ea-958b-0b792b1f0ecb.png)
it pops up this.
As you can see, four icons doesn't show up.
![image](https://user-images.githubusercontent.com/27659768/94158985-9f196a00-feb5-11ea-8976-306f91dbc34d.png)

I've tried four different browser and the promblems above remains still.

**Comment by marubinotto** [comment]
Does the same thing happen when you try the demo server?

https://demo.cotoa.me/

**Comment by li0817** [comment]
> Does the same thing happen when you try the demo server?
> 
> https://demo.cotoa.me/

Yes, I tired it just now. There goes the same problem.
Apart from the buttons I mentioned before, even one more button is missing.
![image](https://user-images.githubusercontent.com/27659768/94874385-716b8c80-0484-11eb-87d7-84eee79e6138.png)

**Comment by marubinotto** [comment]
Probably, your browsers couldn't load the Font Awesome assets for some reason. Can you access the following URL?

https://use.fontawesome.com/47259435b7.js

**Comment by li0817** [comment]
> Probably, your browsers couldn't load the Font Awesome assets for some reason. Can you access the following URL?
> 
> https://use.fontawesome.com/47259435b7.js

Ah! Yes, it does cause the problem, I use proxy to access and it works just fine!

Another question by the way, I've experienced one thing before. All the images and containers are gone after updateing the docker desktop, was that normal? I reinstall the Cotoami but the Cotos inside was totally disappear. Is there any measure to backup I should take?

**Comment by marubinotto** [comment]
I found an issue which may be related to your problem. It was reported on macOS, but I think the same issue could happen in other platforms.

https://github.com/docker/for-mac/issues/1175

So, if you want to protect your data, you should export your data via the Export button on the profile window, which pops up by clicking your avatar icon at the top-right corner, before updating your Docker Desktop.
