### ISSUE TITLE
Disappearing connections

### ISSUE THREAD

**Issue by KnowledgeGarden** [cotoami/cotoami#8]
Make several columns worth of connections. Return another day and refresh page; those columns disappear.  Make another connection and at least some of them reappear. What am I missing?

**Comment by marubinotto** [comment]
Thank you for your feedback!

We are prototyping the UI for making connections. So currently, the connections are ephemeral (not saved in the server) and some features are still missing.

**Comment by KnowledgeGarden** [comment]
Works for me!

**Comment by marubinotto** [comment]
The recent updates (#36, #38) add a feature to save connections on the server-side (graph database). So your connections are not ephemeral anymore!
