### ISSUE TITLE
Split (refactor) a coto

### ISSUE THREAD

**Issue by pihentagy** [cotoami/cotoami#88]
When a coto is getting big, it might need to be split up. There should be some mechanism to refactor that coto.

**Comment by marubinotto** [comment]
Cotoami aims to make coto-inputting as lightweight as possible, so large cotos are exceptional (or you post a large coto intentionally). I think rather we might need a way to merge cotos.

**Comment by pihentagy** [comment]
Yes, but as a beginner you might end up creating a big coto… (yes, this is a mistake)

**Comment by marubinotto** [comment]
After years of experience with Cotoami, I've become to think that big cotos in an initial phase are natural. But I don't feel the need for the automation of splitting a coto.
