### ISSUE TITLE
Hide pinned cotos view

### ISSUE THREAD

**Issue by pihentagy** [cotoami/cotoami#89]
If I deep into another element, pinned elements (or even the timeline) is clutter for me and I'd like to hide it temporarily.

**Comment by marubinotto** [comment]
How about the current UI for narrow viewport (mobile devices)? You can try it by narrowing your browser window on your PC.

**Comment by pihentagy** [comment]
If one needs more column when discovering, it does not help.

**Comment by marubinotto** [comment]
OK. I'd like to hear from others on this.
